# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_auto_20180501_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_no', models.IntegerField(db_column='ANSWER_NO')),
                ('answer_desc', models.CharField(db_column='ANSWER_DESC', max_length=255)),
            ],
            options={
                'db_table': 'RAM_ANSWERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_answer_number', models.IntegerField(db_column='EMP_ANSWER_NUMBER')),
                ('emp_id', models.ForeignKey(db_column='EMP_ID', on_delete=django.db.models.deletion.CASCADE, to='project.Employee', to_field='empid')),
            ],
            options={
                'db_table': 'RAM_EMP_ANSWER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PeriodQuestion',
            fields=[
                ('period_no', models.AutoField(db_column='PERIOD_NO', primary_key=True, serialize=False)),
                ('date_from', models.DateField(db_column='DATE_FROM')),
                ('date_to', models.DateField(db_column='DATE_TO')),
                ('descreption', models.CharField(db_column='DESCREPTION', max_length=255)),
            ],
            options={
                'db_table': 'RAM_PERIOD_TAB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_no', models.AutoField(db_column='QUESTION_NO', primary_key=True, serialize=False)),
                ('question_desc', models.CharField(db_column='QUESTION_DESC', max_length=400)),
                ('correct_answer_no', models.IntegerField(db_column='CORRECT_ANSWER_NO')),
                ('period_no', models.ForeignKey(db_column='PERIOD_NO', on_delete=django.db.models.deletion.CASCADE, to='ram.PeriodQuestion')),
            ],
            options={
                'db_table': 'RAM_QUESTIONS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='employeeanswer',
            name='question_no',
            field=models.ForeignKey(db_column='QUESTION_NO', on_delete=django.db.models.deletion.CASCADE, to='ram.Questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_no',
            field=models.ForeignKey(db_column='QUESTION_NO', on_delete=django.db.models.deletion.CASCADE, to='ram.Questions'),
        ),
    ]
