# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='periodquestion',
            table='RAM_PERIOD',
        ),
    ]
