# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('ram', '0002_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, db_column='EMP_NAME', max_length=150, null=True)),
                ('emp_dept', models.CharField(blank=True, db_column='EMP_DEPT', max_length=150, null=True)),
                ('emp_mobile', models.CharField(blank=True, db_column='EMP_MOBILE', max_length=15, null=True)),
                ('emp_email', models.CharField(blank=True, db_column='EMP_EMAIL', max_length=50, null=True)),
                ('emp_ext', models.CharField(blank=True, db_column='EMP_EXT', max_length=4, null=True)),
                ('emp_id', models.ForeignKey(blank=True, db_column='EMP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Employee', to_field='empid')),
            ],
            options={
                'db_table': 'RAM_EMP_DATA',
                'managed': True,
            },
        ),
    ]
