# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0002_auto_20180501_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeanswer',
            name='emp_answer_number',
            field=models.IntegerField(blank=True, db_column='EMP_ANSWER_NUMBER', null=True),
        ),
    ]
