# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0003_employeedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeanswer',
            name='is_save',
            field=models.NullBooleanField(db_column='IS_SAVE'),
        ),
        migrations.AddField(
            model_name='employeeanswer',
            name='is_submitted',
            field=models.NullBooleanField(db_column='IS_SUBMITTED'),
        ),
    ]
