# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0003_auto_20180502_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeanswer',
            name='is_save',
            field=models.NullBooleanField(db_column='IS_SAVE'),
        ),
        migrations.AddField(
            model_name='employeeanswer',
            name='is_submitted',
            field=models.NullBooleanField(db_column='IS_SUBMITTED'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question_no',
            field=models.ForeignKey(db_column='QUESTION_NO', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ram.Questions'),
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together=set([('question_no', 'answer_desc')]),
        ),
    ]
