# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0004_auto_20180506_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeanswer',
            name='emp_answer_number',
            field=models.CharField(blank=True, db_column='EMP_ANSWER_NUMBER', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='emp_id',
            field=models.ForeignKey(blank=True, db_column='EMP_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Employee', to_field='empid'),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='question_no',
            field=models.ForeignKey(blank=True, db_column='QUESTION_NO', null=True, on_delete=django.db.models.deletion.CASCADE, to='ram.Questions'),
        ),
    ]
