# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('managerid', models.CharField(blank=True, db_column='ManagerId', max_length=45, null=True)),
                ('depcode', models.IntegerField(blank=True, db_column='DepCode', null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(blank=True, db_column='EmpId', max_length=45, null=True)),
                ('depcode', models.CharField(blank=True, db_column='DepCode', max_length=45, null=True)),
                ('depname', models.CharField(blank=True, db_column='DepName', max_length=45, null=True)),
                ('ismanager', models.CharField(blank=True, db_column='IsManager', max_length=45, null=True)),
                ('ext', models.CharField(blank=True, db_column='Ext', max_length=45, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='JobTitle', max_length=200, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=250)),
                ('start', models.DateField(db_column='Start')),
                ('end', models.DateField()),
                ('teamname', models.CharField(db_column='TeamName', max_length=100)),
                ('desc', models.CharField(db_column='Desc', max_length=250)),
                ('creationby', models.CharField(db_column='CreationBy', max_length=20)),
                ('creationdate', models.DateTimeField(db_column='CreationDate')),
                ('departementid', models.IntegerField(db_column='DepartementId')),
                ('statusid', models.IntegerField(db_column='StatusId')),
                ('openby', models.CharField(db_column='OpenBy', max_length=20)),
                ('opendate', models.DateTimeField(blank=True, db_column='OpenDate', null=True)),
                ('closedby', models.CharField(db_column='ClosedBy', max_length=20)),
                ('closeddate', models.DateTimeField(blank=True, db_column='ClosedDate', null=True)),
                ('cancelby', models.CharField(db_column='CancelBy', max_length=20)),
                ('canceldate', models.DateTimeField(blank=True, db_column='CancelDate', null=True)),
                ('deleted', models.IntegerField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(db_column='Name')),
            ],
            options={
                'db_table': 'project_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField(db_column='ProjectId')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('desc', models.CharField(db_column='Desc', max_length=2500)),
                ('status', models.IntegerField(db_column='Status')),
                ('startdate', models.DateTimeField(db_column='StartDate')),
                ('enddate', models.DateTimeField(db_column='EndDate')),
                ('departementid', models.IntegerField(db_column='DepartementId')),
                ('userid', models.IntegerField(db_column='UserId')),
                ('assigndate', models.DateTimeField(db_column='AssignDate')),
                ('realstartdate', models.DateTimeField(db_column='RealStartDate')),
                ('finishby', models.IntegerField(db_column='FinishBy')),
                ('finishdate', models.DateTimeField(db_column='FinishDate')),
                ('cancelby', models.IntegerField(db_column='CancelBy')),
                ('canceldate', models.DateTimeField(db_column='CancelDate')),
                ('closeby', models.IntegerField(db_column='CloseBy')),
                ('closedate', models.DateTimeField(db_column='CloseDate')),
                ('closereson', models.CharField(db_column='CloseReson', max_length=500)),
                ('lastedit', models.DateTimeField(db_column='LastEdit')),
                ('deleted', models.IntegerField(blank=True, db_column='Deleted', null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(db_column='Name')),
            ],
            options={
                'db_table': 'task_status',
                'managed': False,
            },
        ),
    ]
