# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_employee1_sheet1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApDeptTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.IntegerField(blank=True, db_column='DEPT_CODE', null=True)),
                ('dept_name', models.CharField(blank=True, db_column='DEPT_NAME', max_length=86, null=True)),
                ('branch_code', models.IntegerField(blank=True, db_column='BRANCH_CODE', null=True)),
                ('note', models.CharField(blank=True, db_column='NOTE', max_length=21, null=True)),
                ('manager_code', models.CharField(blank=True, db_column='MANAGER_CODE', max_length=10, null=True)),
                ('manager_title', models.CharField(blank=True, db_column='MANAGER_TITLE', max_length=105, null=True)),
                ('manager_ext', models.CharField(blank=True, db_column='MANAGER_EXT', max_length=4, null=True)),
                ('manager_phone', models.CharField(blank=True, db_column='MANAGER_PHONE', max_length=9, null=True)),
                ('resp_dept_code', models.CharField(blank=True, db_column='RESP_DEPT_CODE', max_length=3, null=True)),
                ('manager_level', models.CharField(blank=True, db_column='MANAGER_LEVEL', max_length=7, null=True)),
                ('authority_a', models.CharField(blank=True, db_column='AUTHORITY_A', max_length=50, null=True)),
                ('authority_b', models.CharField(blank=True, db_column='AUTHORITY_B', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ap_dept_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApfDeptView',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('dept_code', models.CharField(blank=True, db_column='DEPT_CODE', max_length=5, null=True)),
                ('dept_name', models.CharField(blank=True, db_column='DEPT_NAME', max_length=100, null=True)),
                ('resp_dept_code', models.CharField(blank=True, db_column='RESP_DEPT_CODE', max_length=5, null=True)),
                ('resp_dept_name', models.CharField(blank=True, db_column='RESP_DEPT_NAME', max_length=100, null=True)),
                ('manager_title', models.CharField(blank=True, db_column='MANAGER_TITLE', max_length=100, null=True)),
                ('manager_ext', models.CharField(blank=True, db_column='MANAGER_EXT', max_length=100, null=True)),
                ('manager_name', models.CharField(blank=True, db_column='MANAGER_NAME', max_length=100, null=True)),
                ('manager_code', models.CharField(blank=True, db_column='MANAGER_CODE', max_length=20, null=True)),
                ('note', models.CharField(blank=True, db_column='NOTE', max_length=200, null=True)),
                ('city_name', models.CharField(blank=True, db_column='CITY_NAME', max_length=100, null=True)),
                ('city_code', models.CharField(blank=True, db_column='CITY_CODE', max_length=20, null=True)),
                ('branch_name', models.CharField(blank=True, db_column='BRANCH_NAME', max_length=100, null=True)),
                ('branch_code', models.IntegerField(blank=True, db_column='BRANCH_CODE', null=True)),
            ],
            options={
                'db_table': 'apf_dept_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('deptauthcode', models.CharField(blank=True, db_column='DeptAuthCode', max_length=10, null=True)),
                ('start', models.DateTimeField(blank=True, db_column='Start', null=True)),
                ('end', models.DateTimeField(blank=True, db_column='End', null=True)),
                ('expired', models.CharField(blank=True, db_column='Expired', max_length=1, null=True)),
            ],
            options={
                'db_table': 'delegation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField(db_column='ProjectId')),
                ('taskid', models.IntegerField(db_column='TaskId')),
                ('actionname', models.IntegerField(db_column='ActionName')),
                ('actiondate', models.IntegerField(db_column='ActionDate')),
                ('notes', models.IntegerField(db_column='Notes')),
            ],
            options={
                'db_table': 'task_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VDeptsheetsdata',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('deptcode', models.IntegerField(blank=True, db_column='DeptCode', null=True)),
                ('deptname', models.CharField(blank=True, db_column='DeptName', max_length=200, null=True)),
                ('mangerid', models.CharField(blank=True, db_column='MangerID', max_length=45, null=True)),
                ('empname', models.CharField(blank=True, db_column='EmpName', max_length=255, null=True)),
                ('totaltask', models.BigIntegerField(db_column='TotalTask')),
                ('done', models.BigIntegerField(blank=True, db_column='Done', null=True)),
                ('inprogress', models.BigIntegerField(blank=True, db_column='INPROGRESS', null=True)),
                ('notcomplete', models.BigIntegerField(blank=True, db_column='NOTCOMPLETE', null=True)),
                ('new', models.BigIntegerField(blank=True, db_column='NEW', null=True)),
            ],
            options={
                'db_table': 'v_deptsheetsdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VSheetsdata',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('employeeid', models.CharField(blank=True, db_column='EmployeeId', max_length=45, null=True)),
                ('employeename', models.CharField(blank=True, db_column='EmployeeName', max_length=255, null=True)),
                ('deptname', models.CharField(blank=True, db_column='DeptName', max_length=200, null=True)),
                ('deptcode', models.CharField(blank=True, db_column='DeptCode', max_length=45, null=True)),
                ('managername', models.CharField(blank=True, db_column='ManagerName', max_length=255, null=True)),
                ('totaltask', models.BigIntegerField(db_column='TotalTask')),
                ('notsubmitted', models.BigIntegerField(blank=True, db_column='NotSubmitted', null=True)),
                ('submitted', models.BigIntegerField(blank=True, db_column='Submitted', null=True)),
                ('new', models.BigIntegerField(blank=True, db_column='New', null=True)),
            ],
            options={
                'db_table': 'V_SheetsData',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Employee1',
        ),
    ]
